# -*- coding: utf-8 -*-
"""IBPAD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2TRPHMWoc3pc2YmFY01ewz3VdScV64p
"""

##!pip install requests
import pandas as pd
import numpy as np
import requests

raw_data  = {'size ': '10000'}
request = requests.get("https://imunizacao-es.saude.gov.br/_search?scroll=132m",auth=('imunizacao_public', 'qlto5t&7r_@+#Tlstigi'))
#request.json()
#request.json()['hits']['hits']
df_minsaude= pd.json_normalize(data= request.json()['hits']['hits'])
#df_minsaude

from scipy.stats import zscore
threshold =2
df_minsaude['zscore.paciente_idade'] = zscore(df_minsaude['_source.paciente_idade'])
df_minsaude['outliers'] = np.where((df_minsaude['zscore.paciente_idade'] - threshold > 0), True, np.where(df_minsaude['zscore.paciente_idade'] + threshold < 0, True, False))
df_minsaude.drop(df_minsaude[df_minsaude['outliers'] == True].index,inplace=True)

df_minsaude =df_minsaude.drop(columns ='_index')
df_minsaude = df_minsaude.drop(columns ='_type')
df_minsaude["_source.estabelecimento_valor"]=df_minsaude["_source.estabelecimento_valor"].astype(int)#remoção de erro int64 ao fazer o marge
df_minsaude

url='https://sage.saude.gov.br/dados/repositorio/cadastro_estabelecimentos_cnes.zip'

import requests
import io
import zipfile

response = requests.get(url)
arquivo=  zipfile.ZipFile(io.BytesIO(response.content))
csv=arquivo.extract(member='cadastro_estabelecimentos_cnes.csv')
csvpd = pd.read_csv(csv,sep=';')
csvpd["_source.estabelecimento_valor"] = csvpd["CNES"] 
#Após alguns testes, e após algumas analises do DataFrame, pode-se concluir, que o  CNES está respresentado  nas 2 bases de dados, sendo possivel
#realizar um margin left e acrecentar os dados adicionais dos postos de vacina.
csvpd['_source.estabelecimento_valor']=csvpd['_source.estabelecimento_valor'].astype(int) #remoção de erro int64 ao fazer o marge
csvpd

#result = df_minsaude.concat(right= csvpd,on='_source.estabelecimento_valor',how='left')
#result

result = df_minsaude.merge( csvpd, on=["_source.estabelecimento_valor"], how="left")
result

a=result.to_csv('base_vacinados.csv',header=False,sep=';')

b=result.to_excel('base_vacinados.xlsx', header=False)

